#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# github.com/dominiksalvet/sandbox
#-------------------------------------------------------------------------------

matrix:
  include:
  - rvm: 2.2
  - rvm: 2.5

script: true
