#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# github.com/dominiksalvet/sandbox
#-------------------------------------------------------------------------------

language: shell

matrix:
  include:
    os:
      - linux
      - osx
      - windows

jobs:
  include:
    - stage: Stage 1
      name: Name 1
      script: true
