#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# github.com/dominiksalvet/sandbox
#-------------------------------------------------------------------------------

os:
  - linux
  - osx

script: true
