name: CI
on: push

jobs:
  JobLinux:
    runs-on: ubuntu-latest
    steps:
    - run: uname

  JobMacos:
    runs-on: macos-latest
    steps:
    - run: echo test

  JobWindows:
    runs-on: windows-latest
    steps:
    - run: uname
