name: CI
on: push

jobs:
  JobLinux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: mkdir -p path/to/artifact

    - run: echo hello > path/to/artifact/world.txt

    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: path/to/artifact/world.txt

  JobMacos:
    runs-on: macos-latest
    steps:
    - run: uname
    - run: echo lol

  JobWindows:
    runs-on: windows-latest
    steps:
    - run: uname
    - run: echo lol

  JobWSL:
    runs-on: windows-2019
    steps:
    - uses: Vampire/setup-wsl@v1
      with:
        distribution: Ubuntu-20.04
    - run: uname
    - run: echo lol
