name: CI
on: push

jobs:
  JobLinux:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo just a test > file.txt
        false
    - if: failure()
      run: cat file.txt

  JobMacos:
    runs-on: macos-latest
    steps:
    - run: uname

  JobWindows:
    runs-on: windows-latest
    steps:
    - run: uname
