name: CI
on: push

jobs:
  JobLinux:
    runs-on: ubuntu-latest
    steps:
    - run: uname

  JobMacos:
    runs-on: linux
    steps:
    - run: uname -a

  JobWindows:
    runs-on: windows-latest
    steps:
    - run: uname
